name: JavaWorkshop

version: 1.0

main: MyPlugin

commands:
  bauBlock:
    description: baut einen Block
  flyingSpeed:
    description: sets flying Speed
  walkingSpeed:
    description: sets walking speed
  testYaw:
    description: test the yaw
  toggleblockplacing
    description: toggles block placing behind you