name: JavaWorkshop

version: 1.0

main: main.MyPlugin

commands:
  bauBlock:
    description: baut einen Block
  flyingSpeed:
    description: sets flying Speed
  walkingSpeed:
    description: sets walking speed
  testYaw:
    description: test the yaw
  spawnSkeletonHorse:
    description: spawns a Skeleton Horse
  test:
    description: test
  toggleblockbreak:
    description: toggles Block break
  labyrinth:
    description: builds labyrinth
  startnewgame:
    description: starts new game
  joingame:
    description: joins the game that is active on the server
  endGame:
    description: ends game on the server prematurely - only available to game creator and thecodx
  test:
    description: test command für alles mögliche